[package]
name = "xor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[target.'cfg(target_os = "linux")']

[dependencies]
base64 = "0.13"
async-std = { version = "1.12.0", features = ["attributes", "async-io"] }